### ISSUE TITLE
Report Issues

### ISSUE THREAD

**Issue by ssp6** [dragorhast/app#25]
### Sprint Number
3
### Extra info

To start with the only issues that can be reported are general then 1's associated with a bike
### Steps to solve
1. [x] Create redux  store with bike issues (nothing really has to be stored there yet
2. [x] Create actions file
3. [x] Create action that hits db with bikeID + message
4. [x] Create a Container that passes through that action
5. [x] Create a page the reporting page with the basics (text box, 2 checks + bikeID that only displays if  checked)

**Comment by Goddessmaatmaat** [comment]
Skip to content
IBM Cloud

        Goddess maat's Account

Status
Planned maintenance
Subscribe to RSS feed
Search
				
	PLANNED: Migrate the Git repository and issue tracking database
	PLANNED: Migrate the Git repository and issue tracking service
	PLANNED: Update the TLS certificates (some clusters only)
	PLANNED: Update the TLS certificates (some clusters only)
PLANNED: Migrate the Git repository and issue tracking database
Component: Continuous Delivery
Location: Dallas
Start time: 2 Feb 2019 6:00 PM
End time: 2 Feb 2019 7:00 PM
Update time: 30 Jan 2019 11:22 AM
Type: Maintenance
ID: 916736
Update Description: We will migrate the Git repository and issue tracking database to a new cluster. This step is one of the steps toward migrating to a more resilient multi-zone architecture. There will not be any visible changes to end users after the update is completed.

Maintenance Duration: 60 minutes

Type of Disruption: Other

Disruption Description: Git Repos and Issue Tracking will be in read-only mode for approximately 20 minutes while the underlying database is migrated to a more resilient multi-zone architecture. Existing user interface sessions will continue to work, but write operations will not be possible. You will not be able to create new user interface sessions while the application is in read-only mode. You will be able to access Git clones using the command line over HTTPS while it is in the read-only mode. However, accessing Git clones using SSH will not be possible. Continuous Delivery Pipeline build jobs will not be affected.

Disruption Duration: 20 minutes
